### ISSUE TITLE
github.com/caddy-dns/namedotcom is not a registered Caddy module package path

### ISSUE THREAD

**Issue by codesplode** [caddy-dns/namedotcom#3]
I am trying to use the `caddy add-package github.com/caddy-dns/namedotcom` to install this plugin, but receive the following error:

```
caddy add-package github.com/caddy-dns/namedotcom
2024/05/31 19:30:10.551	INFO	this executable will be replaced	{"path": "/usr/bin/caddy"}
2024/05/31 19:30:10.551	INFO	requesting build	{"os": "linux", "arch": "amd64", "packages": ["github.com/caddy-dns/namedotcom"]}
Error: download failed: download failed: HTTP 400: github.com/caddy-dns/namedotcom is not a registered Caddy module package path (id=4eda9295-8ae5-4374-a922-81ae28d1d70b)
```

I noticed that this package is not listed on the caddy website with the other dns packages as well, so perhaps there is a configuration issue?

Happy to test and support in any way needed and thank you for the awesome project!

**Comment by ghost** [comment]
The package is now registered with caddyserver.com. Hope that helps.

**Comment by mholt** [comment]
Thank you for registering it!

**Comment by codesplode** [comment]
Thank you @zkyzx. Package is installed and confirmed!
